[project]
name = "aibox"
version = "0.1.5"
description = "My AI utilities and helpers"
authors = [
    # { name = "Daniel Capecci", email = "7775585+dk0d@users.noreply.github.com" },
]
dependencies = [
    "tomlkit>=0.11.6",
    "tqdm>=4.64.1",
    "pyyaml>=6.0",
    "pandas>=1.5.3",
    "omegaconf>=2.3.0",
    "ipython>=8.11.0",
    "matplotlib>=3.7.0",
    "torchinstaller>=0.4.2",
    "rich>=13.3.1",
]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = { text = "MIT" }


[project.urls]

[project.optional-dependencies]
torch = [
    "torch>=1.13.1",
    "torchvision>=0.14.1",
    "torchaudio>=0.13.1",
    "pytorch-lightning>=1.9.4",
]

[tool.pdm.scripts]
test = "pytest tests"

[tool.pdm.build]
package-dir = "aibox/aibox"
includes = []

[tool.pdm.dev-dependencies]
test = ["pytest>=7.2.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
