[tool.poetry]
name = "aibox"
version = "0.1.0"
description = "My AI utilities and helpers"
authors = ["Daniel Capecci <7775585+dk0d@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tomlkit = "^0.11.7"
tqdm = "^4.65.0"
pyyaml = "^6.0"
pandas = "^1.5.3"
omegaconf = "^2.3.0"
ipython = "^8.12.0"
matplotlib = "^3.7.1"
torchinstaller = "^0.5.8"
rich = "^13.3.3"

[tool.poetry.group.torch.dependencies]
pytorch-lightning = "^2.0.1"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
