[project]
name = "aibox"
version = "0.1.0"
description = "My AI utilities and helpers"
authors = [
    { name = "Daniel Capecci", email = "7775585+dk0d@users.noreply.github.com" },
]
dependencies = [
    "tomlkit>=0.11.6",
    "tqdm>=4.64.1",
    "pyyaml>=6.0",
    "pandas>=1.5.3",
    "omegaconf>=2.3.0",
    "ipython>=8.11.0",
    "matplotlib>=3.7.0",
]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]

[tool.pdm]

[tool.pdm.build]
includes = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
